#!/bin/zsh
function countDuplicates() {
    input=$1
    echo "Input string: $input"
    echo "Repeated letters and their counts:"
    echo "$input" | grep -o . | sort | uniq -d -c
}

countDuplicates "$1"
