#!/bin/zsh
# Program Information
    # Valerie's Shell Script for SSH connections
    # Primarily used to log in to York University servers.
    # Has 3 options, -c, -d, and no argument.
    # -c: Connect to a custom ssh address with the default username.
    # -d: Connect to the default ssh address with the default username. 
    # No argument: will ask the user which address to connect to with which username.

# Defaults
    # Address ($adr): red1.eecs.yorku.ca
    # Username ($usrin): gabeg25


# Begin Shell Script

# Introduce the user to the program.
echo "Valerie's Script to login to York's System. For help, run the program with the -help flag. Cancel logins anytime with ^C (Control-C)"

# Check if the argument is "-d".
if [[ $1 == "-d" ]]; then
# If argument is "-d", login with default parameters.
echo "Logging in as gabeg25 on default system red.eecs.yorku.ca"
ssh gabeg25@red.eecs.yorku.ca
fi

# Check if the argument is "-c". 
# Note: Will be overridden if argument is "-d"
if [[ $1 == "-c" ]]; then
# If argument is "-c", login as gabeg25 on the specified system.
echo "Logging in as gabeg25 on system $2 "
ssh gabeg25@$2 
fi

# Check if no argument is given
if [[ $1 == "" ]]; then
# If no argument is given, ask the user for an address and username to use.
echo "Please enter ssh address: "
read adr
echo "Please enter username: "
read usrin

echo "Logging in as $usrin on remote machine $adr"
ssh $usrin@$adr
fi

# If argument is -help, print a short help text.
if [[ $1 == "-help" ]]; then
echo "Arguments: "
echo "-d: Login with default parameters. "
echo "-c: Login with custom address (second argument is the address)"
echo "No Argument: ask which address and username to use."
echo "-help: show this page."
fi

# End of file. 
